export const options = [
  {
    id: 1,
    option: 'Kitchen',
    icon: 'icon-cup-hot',
    fill: '#101828',
    stroke: 'none',
  },
  {
    id: 2,
    option: 'Automatic',
    icon: 'icon-diagram',
    fill: '#101828',
    stroke: 'none',
  },
  {
    id: 3,
    option: 'Petrol',
    icon: 'icon-fuel-pump',
    fill: '#101828',
    stroke: 'none',
  },
  {
    id: 4,
    option: 'Gas',
    icon: 'icon-hugeicons_gas-stove',
    fill: 'none',
    stroke: '#101828',
  },
  {
    id: 5,
    option: 'Water',
    icon: 'icon-ion_water-outline',
    fill: 'none',
    stroke: '#101828',
  },
  {
    id: 6,
    option: 'Microwave',
    icon: 'icon-lucide_microwave',
    fill: 'none',
    stroke: '#101828',
  },
  {
    id: 7,
    option: 'Bathroom',
    icon: 'icon-ph_shower',
    fill: ' #101828',
    stroke: 'none',
  },
  {
    id: 8,
    option: 'Refrigerator',
    icon: 'icon-solar_fridge-outline',
    fill: ' #101828',
    stroke: 'none',
  },
  { id: 9, option: 'TV', icon: 'icon-tv', fill: ' #101828', stroke: 'none' },
  {
    id: 10,
    option: 'Radio',
    icon: 'icon-ui-radios',
    fill: ' #101828',
    stroke: 'none',
  },
  { id: 11, option: 'AC', icon: 'icon-wind', fill: ' #101828', stroke: 'none' },
];
